name: Azure Static Web Apps CI/CD

trigger:
  branches: { include: [ main ] }
  paths:
    include: [ src/App/web/** ]

pr:
  branches: { include: [ main ] }
  paths:
    include: [ src/App/web/** ]

jobs:
- job: build_and_deploy_frontend
  displayName: Build and Deploy React to SWA
  pool:
    vmImage: ubuntu-latest
  steps:
    - checkout: self

    - task: NodeTool@0
      inputs: { versionSpec: '20' }

    - script: |
        cd src/App/web
        export VITE_API_BASE_URL="$(API_BASE_URL)"
        npm ci
        npm run build
      displayName: Build (Vite)

    # Nahraj již postavený obsah do SWA (skip build v tasku)
    - task: AzureStaticWebApp@0
      displayName: Upload to Azure Static Web Apps
      inputs:
        azure_static_web_apps_api_token: $(SWA_DEPLOYMENT_TOKEN)  # SECRET!
        app_location: "src/App/web"
        output_location: "dist"
        skip_app_build: true
