name: Azure Static Web Apps CI/CD

trigger:
  branches: { include: [ main ] }
  paths:
    include: [ src/Frontend/** ]

pr:
  branches: { include: [ main ] }
  paths:
    include: [ src/Frontend/** ]

jobs:
- job: build_and_deploy_frontend
  displayName: Build & Deploy React → Azure Static Web Apps
  pool:
    vmImage: ubuntu-latest
  steps:
    - checkout: self
      submodules: true

    # Volitelně připni verzi Node
    - task: NodeTool@0
      displayName: Use Node.js 18.x
      inputs:
        versionSpec: '18'

    # Debug: Show directory structure
    - bash: |
        echo "Current directory:"
        pwd
        echo "Repository structure:"
        ls -la
        echo "Frontend directory:"
        ls -la src/Frontend || echo "src/Frontend not found"
      displayName: Debug directory structure

    # SWA task: provede npm install + build + deploy
    - task: AzureStaticWebApp@0
      displayName: Build + Deploy to SWA
      env:
        # Dostane se do React během buildu
        REACT_APP_API_URL: $(API_BASE_URL)
      inputs:
        # ↓ Secret token z portálu SWA (Manage deployment token)
        azure_static_web_apps_api_token: $(SWA_DEPLOYMENT_TOKEN)
        app_location: '/src/Frontend'  # kde je package.json a index.html
        api_location: ''               # nepoužíváme Functions
        output_location: 'build'       # Build výstup
        skip_api_build: true
