trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/Backend/minesweeper/**

variables:
  nodeVersion: '22.x'

stages:
  - stage: Minesweeper_Backend
    displayName: Minesweeper Backend (Node/TypeScript)
    jobs:
      - job: build_and_deploy_minesweeper
        displayName: Build & Deploy Minesweeper TS Backend
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - checkout: self

          # === Setup Node.js environment ===
          - task: UseNode@1
            displayName: 'Use Node.js $(nodeVersion)'
            inputs:
              version: '$(nodeVersion)'

          # === Install dependencies ===
          - script: |
              set -eux
              cd src/Backend/minesweeper
              echo "Checking for package-lock.json..."
              if [ -f "package-lock.json" ]; then
                echo "Found package-lock.json, using npm ci..."
                npm ci
              else
                echo "No package-lock.json found, using npm install..."
                npm install
              fi
            displayName: 'Install npm dependencies'

          # === Build TypeScript project ===
          - script: |
              set -eux
              cd src/Backend/minesweeper
              echo "Building TypeScript..."
              npm run build

              echo "Verifying build output:"
              test -d dist
              ls -la dist
              echo "OK: Build completed successfully"
            displayName: 'Build TypeScript project'

          # === Stage deployment package ===
          - bash: |
              set -eux
              rm -rf out && mkdir -p out

              # Copy built files from minesweeper
              if [ -d "src/Backend/minesweeper/dist" ]; then
                cp -r src/Backend/minesweeper/dist out/
                echo "Copied dist directory"
              fi

              # Copy package files
              cp src/Backend/minesweeper/package.json out/
              cp src/Backend/minesweeper/package-lock.json out/ 2>/dev/null || echo "No package-lock.json to copy"

              echo "Contents of out directory (before npm install):"
              ls -la out

              # Install production dependencies
              cd out
              echo "Installing production dependencies..."
              if [ -f "package-lock.json" ]; then
                npm ci --omit=dev
              else
                npm install --omit=dev
              fi

              cd ..
              echo "Contents of out directory (final):"
              ls -la out

              # Verify critical files
              test -d out/dist
              test -f out/package.json
              echo "OK (package): All critical files present in out/"
            displayName: 'Stage backend package'

          # === Create deployment archive ===
          - task: ArchiveFiles@2
            displayName: 'Create deployment package'
            inputs:
              rootFolderOrFile: 'out'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/MinesweeperBackend.zip'

          # === Configure App Settings ===
          - task: AzureAppServiceSettings@1
            displayName: 'Configure App Settings'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              appName: '$(WEBAPP_MINESWEEPER_NAME)'
              resourceGroupName: '$(WEBAPP_RG)'
              appSettings: |
                [
                  { "name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "false", "slotSetting": false },
                  { "name": "NODE_ENV", "value": "production", "slotSetting": false },
                  { "name": "WEBSITES_PORT", "value": "5051", "slotSetting": false },
                  { "name": "WEBSITE_RUN_FROM_PACKAGE", "value": "0", "slotSetting": false },
                  { "name": "ENABLE_ORYX_BUILD", "value": "false", "slotSetting": false },
                  { "name": "MINESWEEPER_NODE_PORT", "value": "5051", "slotSetting": false },
                  { "name": "MINESWEEPER_NODE_HOST", "value": "0.0.0.0", "slotSetting": false }
                ]

          # === Set startup command ===
          - task: AzureCLI@2
            displayName: 'Set startup command (Node.js)'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az webapp config set \
                  -g $(WEBAPP_RG) \
                  -n $(WEBAPP_MINESWEEPER_NAME) \
                  --startup-file "node dist/server.js"

          # === Deploy to Azure ===
          - task: AzureWebApp@1
            displayName: 'Deploy to App Service (ZipDeploy)'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              appType: 'webAppLinux'
              appName: '$(WEBAPP_MINESWEEPER_NAME)'
              package: '$(Build.ArtifactStagingDirectory)/MinesweeperBackend.zip'
              runtimeStack: 'NODE|22-lts'
