trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/Backend/minesweeper/**

variables:
  nodeVersion: '22.x'

stages:
  - stage: Minesweeper_Backend
    displayName: Minesweeper Backend (Node/TypeScript)
    jobs:
      - job: build_and_deploy_minesweeper
        displayName: Build & Deploy Minesweeper TS Backend
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - checkout: self

          # === Setup Node.js environment ===
          - task: UseNode@1
            displayName: 'Use Node.js $(nodeVersion)'
            inputs:
              version: '$(nodeVersion)'

          # === Install dependencies (use npm install instead of npm ci if no lock file) ===
          - script: |
              cd src/Backend/minesweeper
              echo "Checking for package-lock.json..."
              if [ -f "package-lock.json" ]; then
                echo "Found package-lock.json, using npm ci..."
                npm ci
              else
                echo "No package-lock.json found, using npm install..."
                npm install
              fi
            displayName: 'Install npm dependencies'

          # === Build TypeScript project ===
          - script: |
              cd src/Backend/minesweeper
              echo "Building TypeScript..."
              npm run build
            displayName: 'Build TypeScript project'

          # === Stage deployment files ===
          - script: |
              set -eux
              mkdir -p src/Backend/out
              cd src/Backend/minesweeper

              # Copy built JS + package.json + node_modules (prod only)
              cp -r dist ../out/
              cp package.json ../out/
              cp package-lock.json ../out/ 2>/dev/null || echo "No package-lock.json to copy"
              
              cd ../out
              
              echo "Installing production dependencies..."
              if [ -f "package-lock.json" ]; then
                npm ci --omit=dev
              else
                npm install --omit=dev
              fi

              echo "Contents of out directory:"
              ls -la
            displayName: 'Prepare deployment package'

          # === Archive for deployment ===
          - task: ArchiveFiles@2
            displayName: 'Create deployment ZIP'
            inputs:
              rootFolderOrFile: 'src/Backend/out'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/MinesweeperBackend.zip'

          # === Configure App Settings ===
          - task: AzureAppServiceSettings@1
            displayName: 'Configure Azure App Settings (Node backend)'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              appName: '$(WEBAPP_MINESWEEPER_NAME)'
              resourceGroupName: '$(WEBAPP_RG)'
              appSettings: |
                [
                  { "name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "false", "slotSetting": false },
                  { "name": "NODE_ENV", "value": "production", "slotSetting": false },
                  { "name": "PORT", "value": "5051", "slotSetting": false },
                  { "name": "WEBSITES_PORT", "value": "5051", "slotSetting": false },
                  { "name": "ENABLE_ORYX_BUILD", "value": "false", "slotSetting": false },
                  { "name": "MINESWEEPER_NODE_PORT", "value": "5051", "slotSetting": false },
                  { "name": "MINESWEEPER_NODE_HOST", "value": "0.0.0.0", "slotSetting": false }
                ]

          # === Startup configuration (Node) ===
          - task: AzureCLI@2
            displayName: 'Set startup command (Node.js backend)'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az webapp config set \
                  -g $(WEBAPP_RG) \
                  -n $(WEBAPP_MINESWEEPER_NAME) \
                  --startup-file "node dist/server.js"

          # === Deploy ===
          - task: AzureWebApp@1
            displayName: 'Deploy Minesweeper backend to Azure'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              appType: 'webAppLinux'
              appName: '$(WEBAPP_MINESWEEPER_NAME)'
              package: '$(Build.ArtifactStagingDirectory)/MinesweeperBackend.zip'
              runtimeStack: 'NODE|22-lts'