name: Azure Static Web Apps CI/CD

trigger:
  branches: { include: [ main ] }
  paths:
    include: [ src/Frontend/** ]

pr:
  branches: { include: [ main ] }
  paths:
    include: [ src/Frontend/** ]

jobs:
- job: build_and_deploy_frontend
  displayName: Build & Deploy React → Azure Static Web Apps
  pool:
    vmImage: ubuntu-latest
  steps:
    - checkout: self

    # Volitelně připni verzi Node
    - task: NodeTool@0
      inputs:
        versionSpec: '18'

    # SWA task: provede npm install + build + deploy
    - task: AzureStaticWebApp@0
      displayName: Build + Deploy to SWA
      env:
        # Dostane se do Vite během buildu
        VITE_API_BASE_URL: $(API_BASE_URL)
      inputs:
        # ↓ Secret token z portálu SWA (Manage deployment token)
        azure_static_web_apps_api_token: $(SWA_DEPLOYMENT_TOKEN)
        app_location: 'src/frontend'  # kde je package.json a index.html
        api_location: ''              # nepoužíváme Functions
        output_location: 'build'      # Build výstup
